#+LATEX_CLASS: lecture-document-udlap
#+TITLE:
#+OPTIONS: H:1 toc:nil
#+HTML_DOCTYPE:

#+BEGIN_EXPORT latex
\renewcommand{\thecareer}{Department of Computing, Elecronics, and Mechatronics}
\renewcommand{\thedocumenttitle}{Syllabus}
\renewcommand{\theterm}{Spring 2018}
\renewcommand{\thecoursename}{Network and Server Administration}
\renewcommand{\thecoursecode}{LIS4081}
\makeheadfoot
#+END_EXPORT

* General Objective
At the end of this course, students will be able to install and manage servers, backup,
and recover data stored on servers.

* Student Learning Outcomes
By the end of this course, students will be able to:

  + Implement a server.
  + Manage services.
  + Create virtual stances.
  + Backup and rescue servers.
  + Create basic automatic services.

* Course Prerequisites
This course does not have any prerequisites

* Contents

#+LATEX: \begin{multicols}{2}
1. Introduction to Servers
2. Server Operating Systems
   1. Comercial Operating Systems
   2. Open Source Operating Systems
3. Server Installation
4. Application Management
5. Server Administration
6. Data Base Administration
7. Virtualization
8. Containers
9. Backup and Recovery
#+LATEX: \end{multicols}

* Evaluation Criteria and Evaluation Dates

+ Elements of Assessment
  - Homework: 4 deliverables 60%
  - Partial Exams: 30%
  - Final Exam: 20%
+ General Policy
  - It is student’s responsibility to stay in campus or near this until the last
    day of final exams, which can be scheduled for a period of ten working days
    after the final day of lectures.
  - It is advised to attend all lectures.
  - The delivery of homeworks and projects in the set time is important. NO
    assignments will be accepted out of time. Work submitted late (with
    justification) will be assessed on 80% of its original value. No assignments
    will be accepted more than one week late.
  - The student requires 80% attendance to be eligible to present the final
    test.
  - Any case of plagiarism or academic fraud is punishable by a 0 (zero) in the
    task or job in question. If a student commits fraud for a second time, the
    case will be presented to the Board of the Department, where the penalty
    will be determined.
  - http://comunidad.udlap.mx/departamentos/normatividad/Documents/Estudiantes_General%20Reglamento.pdf

* Recomended and Supplementary textbooks
#+LATEX: \renewcommand{\labelenumi}{[\arabic{enumi}]}
1. Negus, C. Linux Bible. https://books.google.com.mx/books?id=c-zGBwAAQBAJ.
   Wiley.
2. Rash, M. Linux Firewalls: Attack Detection and Response with iptables, psad,
   and fwsnort. https://books.google.com.mx/books?id=Ad9Fnk9C7QsC. 2007.
   No Starch Press.
3. Garfinkel, S., Spafford, G., & Schwartz, A. Practical UNIX and Internet
   Security: Securing Solaris, Mac OS X, Linux & Free BSD.
   https://books.google.com.mx/books?id=50maN7VmpusC. 2003. O'Reilly Media.
4. Nemeth, E., Snyder, G., Hein, T.R., Whaley, B., Mackin, D.
   UNIX and Linux System Administration Handbook.
   https://books.google.com.mx/books?id=f7M1DwAAQBAJ. 2017. Pearson Education.
5. von Hagen, W., Jones, B.K. Linux Server Hacks, Volume Two: Tips & Tools for
   Connecting, Monitoring, and Troubleshooting.
   https://books.google.com.mx/books?id=iAh6mU_sjgsC. 2005. O'Reilly Media.

* Lecturer
+ PhD. Juan Carlos Galán Hernández
+ E-Mail [[mailto:juan.galan@udlap.mx][juan.galan@udlap.mx]]
+ Room: LA202
+ Office Hours: *Friday* 13:00 - 15:00
+ Personal Web Page: [[http://juancgalan.com/]]
+ Lecture Resources: https://winliveudlap.sharepoint.com/sites/lis4081
